# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Jiesong Liu's Homepage"
title_separator          : "-"
name                     : &name "Jiesong Liu"
description              : &description "Ph.D. Student at North Carolina State University"
url                      : https://fred1031.github.io
baseurl                  : ""
repository               : "academicpages/academicpages.github.io"

# Site Author (Profile Settings)
author:
  avatar           : "profile.png"
  name             : "Jiesong Liu"
  bio              : "Ph.D. Student at North Carolina State University"
  location         : "Raleigh, NC, USA"
  email            : "jliu93@ncsu.edu"
  googlescholar    : "https://scholar.google.com/citations?user=Lc0FQ1kAAAAJ"

# Only Keep Publications
publication_category:
  conferences:
    title: 'Conference Papers'
  manuscripts:
    title: 'Journal Articles'

# Remove Everything Else Except Publications
collections:
  publications:
    output: true
    permalink: /:collection/:path/

# Remove Sidebar Sections
defaults:
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: false  # Hide sidebar author info
      share: false
      comments: false

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-sitemap
  - jemoji

# Archives: Keep Only Categories for Publications
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Disable Social Media, SEO, and Analytics
analytics:
  provider: "false"

compress_html:
  clippings: all
  ignore:
    envs: development
